"use client";

import { Sparkles } from "lucide-react";
import { Fragment, useId, type ReactNode } from "react";
import { useAiStatus } from "@/lib/ai/client";
import type { AiSource } from "@/lib/types";
import { cn } from "@/lib/utils";

export function AiSpark({ className }: { className?: string }) {
  const g = `spark-g-${useId()}`;
  return (
    <svg viewBox="0 0 24 24" className={cn("size-4", className)} aria-hidden>
      <defs>
        <linearGradient id={g} x1="0" y1="0" x2="1" y2="1">
          <stop offset="0" stopColor="#ff385c" />
          <stop offset="1" stopColor="#92174d" />
        </linearGradient>
      </defs>
      <path d="M12 2.5l2.2 6.3 6.3 2.2-6.3 2.2L12 19.5l-2.2-6.3L3.5 11l6.3-2.2L12 2.5Z" fill={`url(#${g})`} />
      <path d="M19 15.5l.8 2.2 2.2.8-2.2.8-.8 2.2-.8-2.2-2.2-.8 2.2-.8.8-2.2Z" fill={`url(#${g})`} />
    </svg>
  );
}

/** Shows which engine produced a result. */
export function SourceBadge({ source, className }: { source?: AiSource; className?: string }) {
  if (!source) return null;
  return (
    <span
      className={cn("inline-flex items-center gap-1 rounded-full border border-line-soft bg-white px-2 py-0.5 text-[11px] font-semibold text-ink-2", className)}
      title={source === "claude" ? "Generated by Claude" : "Generated by CreatorAI's built-in engine (add ANTHROPIC_API_KEY to use Claude)"}
    >
      <Sparkles className="size-3" />
      {source === "claude" ? "Claude" : "Built-in AI"}
    </span>
  );
}

export function EngineStatus({ className }: { className?: string }) {
  const s = useAiStatus();
  if (!s) return null;
  return (
    <span className={cn("inline-flex items-center gap-1.5 text-xs text-ink-2", className)}>
      <span className={cn("size-1.5 rounded-full", s.claude ? "bg-babu" : "bg-amber")} />
      {s.claude ? "Claude connected" : "Built-in AI · add API key for Claude"}
    </span>
  );
}

export function AiThinking({ label = "Thinking", className }: { label?: string; className?: string }) {
  return (
    <span className={cn("inline-flex items-center gap-2 text-sm font-medium text-ink-2", className)}>
      <AiSpark className="size-4 animate-pulse" />
      <span className="ai-text font-semibold">{label}</span>
      <span className="inline-flex gap-0.5">
        {[0, 1, 2].map((i) => (
          <span key={i} className="size-1 animate-bounce rounded-full bg-ink-3" style={{ animationDelay: `${i * 120}ms` }} />
        ))}
      </span>
    </span>
  );
}

/** Tiny markdown renderer for AI text: **bold**, *italic*, bullet & numbered lists, paragraphs. */
export function Markdown({ text, className }: { text: string; className?: string }) {
  const blocks = text.replace(/\r/g, "").split(/\n{2,}/);
  return (
    <div className={cn("space-y-3 leading-relaxed", className)}>
      {blocks.map((block, bi) => {
        const lines = block.split("\n");
        const isList = lines.every((l) => /^\s*([-*•]|\d+\.)\s+/.test(l) || /^\s{2,}\S/.test(l));
        if (isList) {
          const ordered = /^\s*\d+\./.test(lines[0]);
          const items: string[] = [];
          for (const l of lines) {
            if (/^\s*([-*•]|\d+\.)\s+/.test(l)) items.push(l.replace(/^\s*([-*•]|\d+\.)\s+/, ""));
            else items[items.length - 1] += "\n" + l.trim();
          }
          const Tag = ordered ? "ol" : "ul";
          return (
            <Tag key={bi} className={cn("space-y-1.5 pl-5", ordered ? "list-decimal" : "list-disc", "marker:text-ink-3")}>
              {items.map((it, ii) => (
                <li key={ii} className="pl-1">
                  {it.split("\n").map((seg, si) => (
                    <Fragment key={si}>
                      {si > 0 && <br />}
                      <Inline text={seg} />
                    </Fragment>
                  ))}
                </li>
              ))}
            </Tag>
          );
        }
        return (
          <p key={bi}>
            {lines.map((l, li) => (
              <Fragment key={li}>
                {li > 0 && <br />}
                <Inline text={l} />
              </Fragment>
            ))}
          </p>
        );
      })}
    </div>
  );
}

function Inline({ text }: { text: string }) {
  const parts: ReactNode[] = [];
  const re = /(\*\*[^*]+\*\*|\*[^*\s][^*]*\*|_[^_]+_)/g;
  let last = 0;
  let m: RegExpExecArray | null;
  let i = 0;
  while ((m = re.exec(text))) {
    if (m.index > last) parts.push(text.slice(last, m.index));
    const t = m[0];
    if (t.startsWith("**")) parts.push(<strong key={i++} className="font-semibold text-ink">{t.slice(2, -2)}</strong>);
    else parts.push(<em key={i++}>{t.slice(1, -1)}</em>);
    last = m.index + t.length;
  }
  if (last < text.length) parts.push(text.slice(last));
  return <>{parts}</>;
}
